# Generated by Django 5.2.3 on 2025-06-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('ubicacion', models.CharField(max_length=50)),
                ('servicios', models.CharField(max_length=150, null=True)),
                ('categoria', models.CharField(max_length=50, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('cantidad_habitaciones', models.IntegerField()),
                ('url_info', models.URLField(max_length=150, null=True)),
            ],
        ),
    ]
