# Generated by Django 5.2.3 on 2025-10-01 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_habitacion_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitacion',
            old_name='cantidad_personas',
            new_name='capacidad',
        ),
        migrations.RenameField(
            model_name='habitacion',
            old_name='titulo',
            new_name='nombre',
        ),
    ]
