# Generated by Django 5.2.3 on 2025-11-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_cantidad_personas_habitacion_capacidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='imagen',
            field=models.URLField(max_length=150, null=True),
        ),
    ]
