# Generated by Django 5.2.3 on 2025-11-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_habitacion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='imagen',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
