"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
#Para configurar los tiempos de vida de tus tokens JWT 
from datetime import timedelta



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Cargar variables desde el archivo .env
load_dotenv(os.path.join(BASE_DIR, '.env'))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"


#Desde que dominio estoy sirviendo nuestra aplicación
#ALLOWED_HOSTS = ["mihotel.com" ,  "127.0.0.1"]
#ARMAR UNA LISTA EN BASE AL STRING LEIDO DEL . ENV , SEPARADO POR " , "

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
     'rest_framework',
     'rest_framework_simplejwt',
    'api',#Registrar la aplicacion creada
    'drf_yasg', 
    'corsheaders',
    
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'api.middleware.SimpleLoggingMiddleware',
     
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



#DJANGO REST FRAMEWORK
REST_FRAMEWORK = { 
    'DEFAULT_PERMISSION_CLASSES' : ( 
        # Todas las vistas, por defecto, exigen estar autenticadas
        'rest_framework.permissions.IsAuthenticated' , 
    ), 
     # El sistema de autenticación por defecto será JWT
    'DEFAULT_AUTHENTICATION_CLASSES' : ( 
        'rest_framework_simplejwt.authentication.JWTAuthentication' , 
    ), 
} 

#Define la duración de los tokens
SIMPLE_JWT = {
    #Cuánto tiempo es válido el token de acceso
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    #Cuánto tiempo es válido el token de actualización
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

#Para permitir la comunicación con el frontend en React
#CORS_ALLOWED_ORIGINS = [
    # "http://localhost:5173",
 #]

CORS_ALLOWED_ORIGINS = os.getenv("CORS_ALLOWED_ORIGINS", "").split(",")



### ---------------- CONFIGURACIÓN PERSONALIZADA  DE LOGGING ---------------- ###

# El logger django captura advertencias y errores del framework

#Indico directorio de logs dónde quiero guardar
LOG_DIR =  BASE_DIR.parent / 'logs'
#En caso de que no exista lo cree
LOG_DIR.mkdir(exist_ok=True)


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  # Permite usar los loggers de Django
    
     # ---------------- FORMATOS ---------------- #
    'formatters':{ # Define el formato del mensaje
        'simple': {'format':"[%(levelname)s] %(name)s: %(message)s"}, # Formato simple para consola
        'detallado' : {'format':"[%(levelname)s] %(asctime)s - %(name)s: %(message)s"}, # Formato detallado para archivos (con fecha y hora)
       
    },
    # Determina dónde se envian los mensajes
    'handlers': { 
        'console': {
            'class': 'logging.StreamHandler',  # muestra los logs en la consola
            'formatter':'simple'

        },
        'file': {
            'class': 'logging.FileHandler', #guardar los logs en archivos
            'filename': LOG_DIR / 'hotel_san_remo_debug.log',
            'formatter':'detallado'
        },
          # Guarda logs específicos de la base de datos
        'file_db':{
            'class':'logging.FileHandler',
            'filename': LOG_DIR / 'consultas_db.log',
            'formatter':'detallado'
        },
         # Guarda logs relacionados con errores importantes del sistema
        'file_error': {
            'class': 'logging.FileHandler',
            'filename': LOG_DIR / 'errores_hotel.log',
            'formatter': 'detallado',
        }
    },
    # Define que es lo que quiere capturar y a dónde
    # Logger principal de la aplicación del hotel
    'loggers': {
        'hotel_san_remo_api': {
            'handlers': ['console', 'file','file_error'],
            'level': 'DEBUG',  # Obtenemos info detallada
            'propagate': True,
        },
        #Logger por defecto de django que registra todo lo que pasa en la app
         # Logger general de Django
        'django':{
            'handlers':['console','file'],
            'level': 'WARNING',  # Solo advertencias o errores
        },
        # Logger de las consultas SQL (trazabilidad de base de datos)
        'django.db.backends':{
            'handlers':['file_db'],
            'level':'WARNING',  # Solo loguea si hay problemas de rendimiento
            'propagate': True
        },
    } 
}
