# Generated by Django 5.2.3 on 2025-06-25 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='titulo')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_personas', models.IntegerField()),
                ('descripcion', models.TextField(null=True)),
                ('estado', models.BooleanField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='api.hotel')),
            ],
        ),
    ]
