# Generated by Django 5.2.3 on 2025-07-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
